### ISSUE TITLE
VIF with dummy-coded variables

### ISSUE THREAD

**Issue by kevingoneill** [easystats/performance#113]
Using the `check_collinearity` function, I recently found a model I've been working on has extremely high VIFs for some of the coefficients. This was strange, because the IVs of the model were totally balanced and uncorrelated. I then found [this paper](https://newprairiepress.org/agstatconference/2012/proceedings/12/), which describes that (and when/why) VIF values can be misleading for models including dummy variables. Sure enough, I re-ran my model using sum contrasts, and the VIFs went down to 1. Since dummy coding is currently default in R, I think it might be helpful for this function to print a warning whenever dummy coding is detected.

**Comment by strengejacke** [comment]
I haven't translated the formulas of the paper you refer to into R code, but when I understand Fox et al. right (https://www.tandfonline.com/doi/abs/10.1080/01621459.1992.10475190), dummy regressors are already taken into account by the underlying code we use here for checking collinearity. Maybe you can say more about this?

**Comment by DominiqueMakowski** [comment]
(nothing to do with this issue but @strengejacke what does the "3 investigators" label mean?)

**Comment by strengejacke** [comment]
![DBGgvSgXsAIpjvR](https://user-images.githubusercontent.com/26301769/77656961-e52c5a00-6f74-11ea-9440-fd6c97111377.jpg)

**Comment by strengejacke** [comment]
> investigation of baffling phenomena

**Comment by DominiqueMakowski** [comment]
must catch up on this reference

**Comment by strengejacke** [comment]
I see that in France this was less popular (Les Trois Jeunes Détectives), mais en allemagne, I think these are even more popular than in the US, where this series originated from... The speakers for the audio books (back in those days a [cassette tape](https://en.wikipedia.org/wiki/Cassette_tape), if you know what that is) are the same as back in 1993. We should have been to a live show some days ago, but due to Corona this was cancelled and new date is somewhen in autumn...

**Comment by mattansb** [comment]
@kevingoneill  Are you creating dummy codes manually? Or are you letter R do it?

**Comment by strengejacke** [comment]
_bump_

**Comment by mattansb** [comment]
When you let R build the dummy coding, this VIF takes the this into account, regardless of the coding scheme used:

``` r
## setup data

Y <- iris$Sepal.Length
X1 <- iris$Species
X2 <- factor(iris$Sepal.Width < median(iris$Sepal.Width))

X1_dummay1 <- as.numeric(X1 == "versicolor")
X1_dummay2 <- as.numeric(X1 == "virginica")

X1a <- X1
contrasts(X1a) <- contr.sum
X2a <- X2
contrasts(X2a) <- contr.sum


## additive model
fit_dummay <- lm(Y ~ X1_dummay1 + X1_dummay2 + X2) # dummy
fit1 <- lm(Y ~ X1 + X2) # contr.treatment
fit2 <- lm(Y ~ X1a + X2a) # contr.sum

performance::check_collinearity(fit_dummay)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>   Parameter  VIF Increased SE
#>  X1_dummay1 1.88         1.37
#>  X1_dummay2 1.53         1.24
#>          X2 1.41         1.19
performance::check_collinearity(fit1)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>         X1 1.41         1.19
#>         X2 1.41         1.19
performance::check_collinearity(fit2)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>        X1a 1.41         1.19
#>        X2a 1.41         1.19
```


However, when interactions are involved, the type of contrast scheme matters:
```R
## moderation (interactions)
fit3 <- lm(Y ~ X1 * X2) # contr.treatment
fit4 <- lm(Y ~ X1a * X2a) # contr.sum

performance::check_collinearity(fit3)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>         X1 3.48         1.87
#> 
#> High Correlation
#> 
#>  Parameter   VIF Increased SE
#>         X2 18.41         4.29
#>      X1:X2 44.40         6.66
performance::check_collinearity(fit4)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>  Parameter  VIF Increased SE
#>        X2a 2.73         1.65
#>    X1a:X2a 3.70         1.92
#> 
#> Moderate Correlation
#> 
#>  Parameter  VIF Increased SE
#>        X1a 5.11         2.26
```

Why? Because VIF (and other collinearity measures) estimate the collinearity for the model *parameters* (or their total combination, for factors). In interactions, the coding scheme can change the meaning of parameters from simple effects (conditional) to main effects (marginal). Effects coding is essentially a "centering" of categorical variables, which affects the collinearity of parameters - e.g. with contiious predictors:

``` r
## setup data

iris$Sepal.Width_c <- scale(iris$Sepal.Width)
iris$Petal.Width_c <- scale(iris$Petal.Width)

fit1 <- lm(Sepal.Length ~ Sepal.Width * Petal.Width, iris)
fit2 <- lm(Sepal.Length ~ Sepal.Width_c * Petal.Width_c, iris)

performance::check_collinearity(fit1)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>    Parameter  VIF Increased SE
#>  Sepal.Width 4.03         2.01
#> 
#> High Correlation
#> 
#>                Parameter   VIF Increased SE
#>              Petal.Width 95.33         9.76
#>  Sepal.Width:Petal.Width 86.00         9.27
performance::check_collinearity(fit2)
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>                    Parameter  VIF Increased SE
#>                Sepal.Width_c 1.30         1.14
#>                Petal.Width_c 1.35         1.16
#>  Sepal.Width_c:Petal.Width_c 1.46         1.21
```

Note that this affects the collinearity of the parameters, but in an uninteresting way - and *doesn't* affect the collinearity of the total model! See the awesome paper by [Olvera Astivia and Kroc, 2018](https://doi.org/10.1177/0013164418817801).

Conclusion:
1. Let R build the dummy variables, don't do it mamually.
2. With interactions, you might want to use an effects coding scheme / center variables. (Again, this only affects the VIF of the parameters, not of the actual main effect / total model).

**Comment by mattansb** [comment]
@strengejacke I think this issue can be closed...

**Comment by strengejacke** [comment]
Ok, I might use parts of your comments on the docs.

**Comment by mattansb** [comment]
Go for it (:

**Comment by kevingoneill** [comment]
Thanks for this! Your explanation helps a lot. Yes I was using R’s default dummy coding scheme in a model with an interaction term
