### ISSUE TITLE
Compute variance explained at different levels (mixed models)

### ISSUE THREAD

**Issue by hauselin** [easystats/performance#114]
**Describe the solution you'd like**
For mixed-effects models (e.g., lme4, nlme), is it possible to compute the relative amount of variance explained **at different levels** when comparing two models? 

**How could we do it?**
This can be done using Hox's (2010) variance reduction approach (pp. 69-78), which is described in [this post](http://philippmasur.de/blog/2018/05/23/how-to-center-in-multilevel-models/).

**Comment by strengejacke** [comment]
I think the post is a bit misleading. What the last function (with reference to Hox) actually does, is following:

```r
library(insight)
1 - (get_variance_random(m1.cmc) / get_variance_random(m0))
#> var.random 
#>  0.8828318 

1 - (get_variance_residual(m1.cmc) / get_variance_residual(m0))
#> var.residual 
#>    0.2504617 
```

So it computes the proportion of residual variances (sigma^2) between two models, and the proportion of variance that can be accounted to random effects (more precise: the between-group variance that is related to the grouping structure, see [details here](https://easystats.github.io/insight/reference/get_variance.html)).

So my question is, looking at the title of this issue: would you like to compute the variance explained on different levels (see here: https://github.com/easystats/performance/issues/78), or would you like to compute a "variance reduction" as shown in the post (see my above code-example)?

FWIW, the topic of the blog post is not just about centering, but actually about correct preparation to account for different sources of variability for variables used at level-1, that also have an effect at level-2. This is called _heterogeneity bias_, and in particular a problem when analyzing panel data. However, instead of using FIxed Effects regression (like economists do), it's better to use a well-specified mixed model. See e.g. [this vignette](https://easystats.github.io/parameters/articles/demean.html) and the related [`demean()`-function](https://easystats.github.io/parameters/reference/demean.html).

**Comment by strengejacke** [comment]
Short addition (don't want to delete my posting). After a second look, I think I got what you mean. The approach by Hox mimics R2-values by always referring the model in question to the the Null-model.

**Comment by strengejacke** [comment]
We could stick the the code I posted above, this would work for models with simpler and more complex random effects structure, however, it always looks at "fixed" and "random" parts, not at level-2, level-3 or whatsoever. So it would yield identical results for simpler cases like shown in the blog-posting.

It would be more difficult to get the explained variance at level-3 (see https://easystats.github.io/performance/reference/icc.html), or when random slopes are present. For nested or cross-classified models _without_ random slope, we could use `insight::get_variance_intercept()` to get the variances at different group-levels.

**Comment by strengejacke** [comment]
r2(m1.nc, by_group = TRUE)
#> # Explained Variance by Level
#> 
#> Level   |    R2
#> ---------------
#> Level 1 | 0.245
#> id      | 0.761

r2(m1.gmc, by_group = TRUE)
#> # Explained Variance by Level
#> 
#> Level   |    R2
#> ---------------
#> Level 1 | 0.245
#> id      | 0.761

r2(m1.cwc, by_group = TRUE)
#> # Explained Variance by Level
#> 
#> Level   |     R2
#> ----------------
#> Level 1 |  0.250
#> id      | -0.053

r2(m1.cmc, by_group = TRUE)
#> # Explained Variance by Level
#> 
#> Level   |    R2
#> ---------------
#> Level 1 | 0.250
#> id      | 0.883

**Comment by strengejacke** [comment]
Just a short remark: this function requires the latest _insight_ version from GitHub.

**Comment by hauselin** [comment]
> Short addition (don't want to delete my posting). After a second look, I think I got what you mean. The approach by Hox mimics R2-values by always referring the model in question to the the Null-model.
> 
> I think this will work for simpler models (see discussion in #78), however, becomes difficult for more complex models ([`r2()`](https://easystats.github.io/performance/reference/r2_nakagawa.html) accounts for these more complex structures).

Thanks for your response and insights! Yes, that's what I meant and I guess I can accomplish it using your _insight_ package.

**Comment by strengejacke** [comment]
after updating insight from GitHub, you can use `r2(model, group_by = TRUE)` to get the explained variance at different levels.

**Comment by hauselin** [comment]
> after updating insight from GitHub, you can use `r2(model, group_by = TRUE)` to get the explained variance at different levels.

Awesome. Thanks for letting me know!

**Comment by strengejacke** [comment]
Yes, see my examples (based on the data and models from the blog post you linked to) here: https://github.com/easystats/performance/issues/114#issuecomment-611435697

That's why I closed this issue, because I think it's solved ;-)
