### ISSUE TITLE
"pca" metrics

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#14]
What else functions could fit into this package? Looking at the scope, I would also say that [some of these functions](https://strengejacke.github.io/sjstats/reference/rmse.html) would also fit into the performance pkg.

**Comment by DominiqueMakowski** [comment]
This would definitely fit. 

Other things that come to my mind when I think of the scope:

-  Other indices used in the structural equation field ([this bunch of guys](https://www.researchgate.net/post/Whats_the_standard_of_fit_indices_in_SEM)). As they are computed by default by lavaan, it would mostly consist of extractors consistent with the easyverse.
- Convenience methods for PCAs / Factor Analysis, returning the % of variance explained.
- I think that in general, and in the future, the easyverse (that *is* a thing now :) methods could be useful in the machine learning world, where people struggle with different models/packages. Providing a unifying syntax for extracting, interpreting and understanding their models could be quite appreciated. Although this will probably wait for the help of a future contributor, expert in this kind of things. But providing the tools to bridge the regression world with the ML world could be quite cool.

**Comment by strengejacke** [comment]
According the 2nd point, I think we can use the code from here:
https://strengejacke.github.io/sjstats/reference/pca.html

**Comment by DominiqueMakowski** [comment]
I've also made a parameters extraction implementation for fa/pca and lavaan in psycho, and I didn't know sjstats had it also (I guess it does too many things 😛)...

**Comment by strengejacke** [comment]
> I guess it does too many things

Yes, that's why an "out-sourcing" into separate packages makes sense. ;-) In the long term, I'll remove those functions from sjstats and just keep a set of useful functions that do not exactly fit into existing easyverse-packages.

**Comment by strengejacke** [comment]
What do think about the name? Currently, we have `pca()` and `pca_rotate()`. What about `item_pca()`, to be more consistent with this "group" of functions?

**Comment by DominiqueMakowski** [comment]
What about integrating the two (similar to [`psych::pca()`](https://www.personality-project.org/r/html/principal.html)) so that the rotation is an argument of the former, which would lower the number of exported functions.

As for the name, pca is good because it is widely known by this name. However, I think the name would clash with psych, which `principal()` seems to have `pca` as an alias. 

We could go full plain with `principal_components()`? or `principal_components_analysis` (as you said, we live in the time of auto-completion ^^)?

`principal_components` make sense tho as the function returns precisely the principal components. Whereas a principal components *analysis* would also possibly refer to other pre/post processing steps.
