### ISSUE TITLE
Information criteria differences and weights 

### ISSUE THREAD

**Issue by bwiernik** [easystats/performance#255]
It would be really nice if either `compare_performance()` or a new `test_ic()` function could compute the difference between information criteria statistics (e.g., AIC) as well as comparison weights, ala `bbmle::ICtab()`. See [here](https://github.com/bbolker/bbmle/blob/master/R/IC.R).

For example:
```
a <- lm(formula = mpg ~ wt + qsec + am, data = mtcars)
b <- lm(formula = mpg ~ wt + qsec, data = mtcars)
n <- lm(formula = mpg ~ 1, data = mtcars)

bbmle::ICtab(a, b, n, base = TRUE, weights = TRUE)
```

**Comment by DominiqueMakowski** [comment]
We discussed the idea of having a way to display differences rather than raw indices (https://github.com/easystats/performance/issues/28#issuecomment-760889762) either through a different function or an argument, but @strengejacke raised concerns whether this applied (and was meaningful) for all indices. Or should we just apply the difference to a subset of pre-determined metrics?

**Comment by bwiernik** [comment]
I think a `test_ic()` function with an argument to specify the information criterion makes the most sense.
