### ISSUE TITLE
equivalence-test for frequentist models

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#27]
When reading [this article](https://www.nature.com/articles/d41586-019-00857-9), that encourages to think of CI as _compatible intervals_, and that there's _always_ a difference (even from NULL) etc., I though about implementing a frequentist-equivalent to the Bayesian `equivalence_test()` we have in bayestestR.

- `rope_range()` would be identical, so we can call `bayestestR::rope_range()`
- `rope()` will differ, because we have no posterior and no HDI, but just the CI. But we don't really need this function, just internally we need to calculate how much of the CI is inside the rope-range. We could probably just check the proportion of overlap of rope in CI.
- `equivalence_test()` will get `.lm`, `.lmer`, `.glm` generics etc., that actually all do the same thing: 1) determine rope-range, 2) compute the xx%-CI, 3) check overlap of CI within rope-range.

This will of cource not completely overcome the dichotomia-problem of significant vs. non-significant, but it shows which predictors might be more under discussion, because their status is "undecided".

**Comment by strengejacke** [comment]
To avoid confusion, and since `equivalence_test()` requires the first argument to be names `posterior`, we should have a different name for this function, though?

**Comment by DominiqueMakowski** [comment]
I just finished reading the article (thanks to your twitter 😄), and I agree. This might be an alternative to [the CET](https://github.com/easystats/parameters/issues/12). As it is a characterisation of the parameters of the model, I would see it in parameters...?

Since `parameters` must reexport `ci()` (now that it is defined in baytestR) and expand it to frequentist models, we might as well just follow this lead and expand the others rope-related functions to frequentist models.

**Comment by DominiqueMakowski** [comment]
True true, we should rename the first argument :)

**Comment by strengejacke** [comment]
Haha, just repeating myself... ^^ Totally forgot that we already discussed this topic.

**Comment by strengejacke** [comment]
Closing in favor of https://github.com/easystats/parameters/issues/12
