### ISSUE TITLE
`compare_performance()` and weighted ICs...

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#392]
@bwiernik should we include or omit the weighted ICs from the performance comparison?

See https://easystats.github.io/see/articles/performance.html#compare-model-performances

**Comment by bwiernik** [comment]
They are IC _weights_, not weighted IC. They are super useful for interpreting whether IC differences are meaningful. So I think they should definitely be in the table. Though we might consider picking just one IC to show by default (eg, just AIC/LOOIC rather than also BIC/WAIC).

Or do you mean in the visualization spider plot?

**Comment by bwiernik** [comment]
@strengejacke They are IC weights, not weighted ICs

**Comment by strengejacke** [comment]
Does the wrong wording appear in any user-visible context? (I have checked news, and there I didn't find "weighted ICs")

**Comment by bwiernik** [comment]
No I fixed it in user visible places, just referring to your comment in the last commit
