### ISSUE TITLE
Assumption checks for `htest` objects

### ISSUE THREAD

**Issue by mattansb** [easystats/performance#401]
Would be nice to be able to check the assumptions:

- `t.test`:
  - equal var (for un-paired)
  - norm of residuals 
- `chisq.test` / `prop.test`
  - N/Cell is > 5 or 10
- `cor.test`
  - multivariate norm?
- `oneway.test`: same as for `aov()`

Etc...

**Comment by rempsyc** [comment]
I would love to see this feature implemented in the future and would certainly use it to stick as much as possible to the easyverse in my workflow. 👌

**Comment by bwiernik** [comment]
> When equal-var is not assumed, is it correct to asses normality for each group separately?

sure. Holm-correct any p values

> for cor.test - only multivariate normality?

yes, this is analogous to normality of residuals

> How to test symmetry for wilcoxon test?

A stat is presented here on page 33 https://etheses.bham.ac.uk/id/eprint/4607/1/Voraprateep13MRes.pdf

**Comment by rempsyc** [comment]
> When equal-var is not assumed, is it correct to asses normality for each group separately?

(For what it's worth) I asked a question about this on StackExchange once, the answer suggested that if you have categorical predictors (e.g., groups), then it is suggested that you check assumptions directly on the raw data rather than on the residuals. I was trying to use `check_model()` for planned contrasts but the resulting figures didn't seem to make too much sense to me.

> The distributional assumptions are the same with categorical predictors as with numerical predictors; namely, the conditional distributions are all assumed to be normal with common variance. However, with categorical predictors you do not have to resort to looking at residuals, because you can investigate the conditional distributions directly by subsetting the data for the different levels of the categorical predictor.

https://stats.stackexchange.com/questions/502175/how-to-test-assumptions-with-a-categorical-predictor-planned-contrasts-in-line/502177#502177

Given that I was advised to rely on diagnostic plots rather than objective tests if possible, the way I've been trying to handle this is e.g.,

```r
rempsyc::nice_normality(data = iris,
                        variable = "Sepal.Length",
                        group = "Species",
                        shapiro = TRUE)
```
![nice_normality](https://user-images.githubusercontent.com/13123390/170287970-398a5a12-0440-4f05-9196-8841dc6533a9.png)

**Comment by bwiernik** [comment]
Residuals and raw data if you only have categorical predictors in a linear model have the same distributional shape, they are only mean-shifted (because the categorical predictors reflect group means).

It is generally preferred to still use residuals so that the mean residual is zero and that things like standardized residuals follow expected distributions (eg, as part of influential points checks or homoskedasticity checks).

**Comment by mattansb** [comment]
> > How to test symmetry for wilcoxon test?
>
> A stat is presented here on page 33 https://etheses.bham.ac.uk/id/eprint/4607/1/Voraprateep13MRes.pdf

``` r
check_symmetry <- function(x, ...) {
  f_ <- bayestestR::density_at(x, x)
  if (var(f_) == 0) {
    Sym <- 0
  } else {
    F_ <- ecdf(x)(x)
    Sym <- -cor(f_, F_)  
  }
  
  Sym
}

check_symmetry(z <- rexp(1000))
#> [1] 0.9375129

check_symmetry(-z)
#> [1] -0.9375129

check_symmetry(x <- rchisq(1000, 3))
#> [1] 0.8415241

check_symmetry(x * 14 + 200)
#> [1] 0.841458

check_symmetry(rchisq(1000, 300))
#> [1] 0.05684856

check_symmetry(rnorm(1000))
#> [1] -0.01754306

check_symmetry(rt(1000, 3))
#> [1] -0.02556873

check_symmetry(runif(1000))
#> [1] 0.3435105
```

<sup>Created on 2022-07-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


Note sure if there is an easy way to actually test that this values is not 0.

**Comment by strengejacke** [comment]
> Note sure if there is an easy way to actually test that this values is not 0.

`value != 0` 😬

**Comment by mattansb** [comment]
![](https://c.tenor.com/sttF8xY21_QAAAAM/goodfellas-henry-hill.gif)

**Comment by DominiqueMakowski** [comment]
It makes sense in check_normality I think

**Comment by IndrajeetPatil** [comment]
I like the parsimonious approach of covering this under `check_normality()`.

**Comment by bwiernik** [comment]
Agreed
