### ISSUE TITLE
Naming of functions

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#41]
@DominiqueMakowski Since we have several functions that compute the model quality or performance, maybe we can find a common prefix for those as well? E.g.

`performance_rmse()`, `performance_epcp()`, `performance_logloss()` etc., or `quality_rmse()`, `quality_epcp()`, `quality_logloss()`.

This would be in line with other "bundles" like `r2_*()`. `item_*()` and `check_*()`. What would you say?

**Comment by DominiqueMakowski** [comment]
definitely. 

I don't know what's the best prefix though...

**Comment by strengejacke** [comment]
> I don't know what's the best prefix though...

Finding prefixes used to be _your_ job, actually. :-)

Pro `performance_*`
- package name, so easy to remember
- `model_performace()` computes those indices we are talking about, to that prefix would fit

Pro `quality_*`
- This is rather a linguistic or maybe conceptional question, whether we present _performance_ or _quality_ measures here, of if they're even the same?

**Comment by DominiqueMakowski** [comment]
I agree with you, `performance_*` is appropriate for pretty much all the functions since they all reflect some aspect of what could be seen as "performance" (in its wide definition). Prefixing all functions with `performance_` as also an initial proposal, dropped because it was too verbose to have `performance_r2_nakagawa`.

The question is then, are *these* candidate metrics (rmse, epcp, logloss) particularly different from all the remaining. i.e., are they forming a particular cluster that would be more specifically designated by "quality"?

**Comment by strengejacke** [comment]
Maybe we should develop some rules according naming conventions ;-)

1. verbosity > prefix (i.e. choose `r2_*` rather than `performance_r2_*`)
2. common prefix (bundles) > single functions
3. ...

;-)

Do we want start using aliases? i.e. `correct_predictions()` and `performance_epcp()`?

**Comment by DominiqueMakowski** [comment]
In general, aliases can be useful, but in this particular case I think once we'll make a decision we'll get used to it, especially since the length of the two alternatives is quite similar. Having two many variants would be more confusing than not. So let's go for `performance_epcp` (or quality 😅), since @pdwaggoner was suggesting that this function is known as is.

**Comment by pdwaggoner** [comment]
Sounds good to me and I agree with @DominiqueMakowski . My only concern here is that technically as constructed, the measure is the `pcp`, not the `epcp`. This is only because the `epcp` relies on post-estimation simulations and then using the calculated posterior mean as the returned value. Since we are only calculating the correctly classified observations based on the model predictions, I would suggest renaming this to `pcp` instead (i.e., `performance_pcp`). Sorry ot be so nit-picky! Perhaps we could consider expanding the function in the future to actually reflect the `epcp`.

**Comment by DominiqueMakowski** [comment]
haha we *are* nit-picky. 

👍 for `performance_pcp`.

**Comment by strengejacke** [comment]
ok, now we have

```r
performance_logloss
performance_mse
performance_pcp
performance_rmse
performance_rse
```

Currently not "grouped" or bundled functions. Should be rename one of those as well?

Here, with my vote in parantheses
- binned_residuals (no)
- cronbachs_alpha (no)
- error_rate (maybe, but which name?)
- hosmer_lemeshow (maybe, but which name?)
- icc (hm... no?)
- predictive_accuracy (probably yes, but which name?)

**Comment by strengejacke** [comment]
> especially since the length of the two alternatives is quite similar

True, but not for `rmse()` and `performance_rmse()`... I'm a but undecided regarding aliases, but I do prefer prefixing the functions.

**Comment by DominiqueMakowski** [comment]
For `rmse` the alias could be useful. I would agree with it.

- binned_residuals: why not, since it returns a plot, it's actually relatively different. Maybe we should in the future consider a cluster for performance plots (under `see`?) with this, ROC curves and other stuff?
- cronbachs_alpha: no, famous name
- error_rate: yes... `performance_error`? Since it's *kinda* the performance related to the error (and its rate?)...
- hosmer_lemeshow: probably. Based on what we did for bayesfactor_savagedickey, we would expect `performance_hosmerlemeshow` but not very elegant. (and neither is savagedickey). Maybe `performance_hosmer` (and `bayesfactor_savage`). It's sad for the second author but...
- icc : no, famous name
- predictive_accuracy: `performance_predicted` or `performance_prediction` would maybe work, as it is the performance (i.e. the accuracy) of the prediction...

**Comment by pdwaggoner** [comment]
And here are a few other ideas to throw in the mix to try to be consistent with the other functions:

```{R}
performance_er # error rate
performance_hl # hosmer_lemeshow
performance_accuracy # predictive accuracy
```

**Comment by strengejacke** [comment]
> Maybe we should in the future consider a cluster for performance plots (under see?) with this, ROC curves and other stuff?

Yes! But this function _only_ returns a plot and has no numerical output.

**Comment by pdwaggoner** [comment]
Not sure if you're referencing the easystats function `binned_residuals` or if you are referencing the ROC option, but in case you are talking about ROC curves, the package `pROC` has some powerful functions for plotting nad numeric output using, e.g., the `roc` function from the package (`pROC::roc`). I could be misunderstanding what you guys are talking about though; so disregard this if I am talking about something else...

**Comment by strengejacke** [comment]
I'm referring to the function `sjstats::binned_resid()`, which I re-implemented here in _performace_. You find details here: https://strengejacke.github.io/sjstats/reference/rmse.html#details

It's a residual-check for logistic regression models proposed by Gelman & Hill.

ROC-curves are definitely something we should keep in mind, maybe here the computational part and in package _see_ the visualization?

**Comment by DominiqueMakowski** [comment]
> ROC-curves are definitely something we should keep in mind, maybe here the computational part and in package see the visualization? 

👍 

and @pdwaggoner, it looks like we like re-implementing stuff "our way" haha (with different argument names ;)

**Comment by strengejacke** [comment]
But in the end, we have the "one ring to rule them all"-set of functions, hopefully ;-)
Like `r2()` for (almost) _any_ model, just like in the _insight_ package, but either for performance indices, or model parameters (pkg _parameters_). I think this can make easystats-packages distinctive from existing packages.

**Comment by strengejacke** [comment]
hm. still not 100% satisfied with both of your suggestions according the new name of `error_rate)`. Since one measure is `pcp` (percentage of correct predictions), and the error-rate is also describes as "percentage of correct deterministic predictions", we could use something like `performance_pcdp()`? or `performance_pdp()`?

**Comment by pdwaggoner** [comment]
I see that. The difference seems to be between the words "correct" and "deterministic". The idea behind "correct" is a mapping of the predicted classes onto the empirical classes, i.e., whether or not the prediction was correct. How do you conceptualize "deterministic" in this sense? 

I have no preferences on the naming, specifically. I just want it to be a name that most accurately describes the function.

**Comment by strengejacke** [comment]
> The error rate is defined as the proportion of cases for which the deterministic prediction—guessing `yi = 1` if `logit^−1(Xiβ) > 0.5` and guessing `yi = 0` if `logit^−1(Xiβ) < 0.5`—is wrong.

_Gelman & Hill 2007, p99_

and later...

> Our final logistic regression model (as calculated in R as shown) has an error rate of 36%. The model correctly predicts the behavior of 64% of the respondents. The error rate is not a perfect summary of model misfit, because it does not distinguish between predictions of 0.6 and 0.9, for example. But, as with R2 for the linear model, it is easy to interpret and is often helpful in understanding the model fit. An error rate equal to the null rate is terrible, and the best possible error rate is zero. Thus, the well-switching model is not particularly impressive with an error rate of 38%, a mere 4% better than simply guessing that all people will switch.

So, it's also about "correct" predictions, but probably less accurate then the PCP.

**Comment by pdwaggoner** [comment]
Yeah that helps - Gelman and Hill are usually right about most things... I am agnostic about the name, given this quote here as they are functionally the same thing. It seems more like a semantics thing at this point. Totally your call.

**Comment by strengejacke** [comment]
Maybe we should integrate both into one functin and add a `method`-argument?

**Comment by pdwaggoner** [comment]
Absolutely. That's a great idea. As is now, I think its a good middle ground, at least as a first step, to have `pcp_herron` and `pcp_gelman_hill`. A method argument shouldn't be too onerous either for future dev

**Comment by strengejacke** [comment]
> at least as a first step, to have pcp_herron and pcp_gelman_hill

As functions, or as `method`-argument-option?

**Comment by pdwaggoner** [comment]
I was thinking some variation of the latter, like (in overly simplified terms):

```{R}
performance_pcp <- function(x, method = c("herron", "gelman_hill), ...)
  if (method == "herron") {
(sum(1 - pr[y == 0]) + sum(pr[y == 1])) / n)
} else  {
1 - mean((pr > .5 & y == 0) | (pr <= .5 & y == 1)) # gelman_hill
}
```

Does this make any sense or am I crazy?

**Comment by strengejacke** [comment]
Ah, ok. Yes, this is how I currently implemented it :-)
just the names differ a bit: `method = c("Herron", "Gelman-Hill")`, but maybe lower case and underscore is better.

**Comment by pdwaggoner** [comment]
OH got ya - sorry I must've missed that. But how you have it is great! This was just off the top of my head. Glad to know we are on the same page :D

**Comment by DominiqueMakowski** [comment]
We need to find a way of standardizing author-method names. Sample issue for bayes factor, either "savage-dickey" "Savage-Dickey" or "savage_dickey" and all.

I am not sure what is the best approach. Since it's a character, preserving the "clean" name ("Gelman-Hill") is not that much of a problem.

Pinging @mattansb as you're not watching this repo not sure if you're notified 👀

**Comment by mattansb** [comment]
For characters it might be the most user-friendly to let them have all the options and do some internal sort of `match.arg` kind of thing. See for example how I implemented the `direction` argument [here](https://github.com/easystats/bayestestR/blob/3df530592fbc8e57388b6052b8e41c62ee21ea62/R/bayesfactor_savagedickey.R#L56).

**Comment by DominiqueMakowski** [comment]
Having "clean" names in the documentation (i.e., the recommended option) and some sort of fuzzy approx. matching in case the user misspecifies it seems like a good alternative.
