### ISSUE TITLE
model_performance for Stan models

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#44]
Looking at the blog-post, two things came to my mind.

1) Should we remove the CI from the R2-values? It really bloats the output.
2) Should we use a lighter theme for the code-chunks? Dark mode was cool for some months when Apple introduced it, but Apple is on the skids and no longer trend setting. I think light themes are better (at least for the code, the sidebar looks good!)

**Comment by DominiqueMakowski** [comment]
1. Yes the output is a bit overcharged 😕  Should we decide to keep for instance only the median, remove the "_median" specifier e basta?
2. I initially didn't like it, but I think it's useful as it contrasts well with text and makes it easier to understand the structure and increases the overall readability. I changed because I felt like the code output and the text was getting mixed with the white theme. But it can be easily changed...

PS: I do have a personal beef with Apple, having actually worked at the apple store for severeral weeks... until they dismissed me in the most uncool fashion 😠 So I am definitely ***not*** taking them as a model 😅.

**Comment by strengejacke** [comment]
> So I am definitely not taking them as a model

No, I did not assume you were doing so ;-) It's just that many things (also, e.g. RStudio, or blogs/themes/...) in general are shipped with default-appearance in the style of Apple.
