### ISSUE TITLE
Plotting residuals vs. fitted

### ISSUE THREAD

**Issue by jebyrnes** [easystats/performance#486]
Hello! Running into a funny error. Consider the following reprex

```
library(palmerpenguins)

mod <- lm(flipper_length_mm ~ bill_length_mm, data = penguins)

check_model(mod, "ncv") |> plot()
```

This throws the error

```
Error: The RStudio 'Plots' window is too small to show this set of plots.
  Please make the window larger.
```

running  R 4.2.1 and RStudio build 544 (the latest stable release).

This also fails when knitting an RMarkdown file.

1)  Can this bug be fixed?
2) I notice there's not a similar `check_*` function to plot just the fitted v. residual. Standardized residual, yes. Raw residual, no. Unless I'm missing something. Does that exist?

**Comment by strengejacke** [comment]
You have to name the argument, the second argument is the dot size, not the checks:

```r
check_model(mod, check = "ncv")
```

**Comment by strengejacke** [comment]
> I notice there's not a similar check_* function to plot just the fitted v. residual. Standardized residual, yes. Raw residual, no. Unless I'm missing something. Does that exist?

No yet, I think. @bwiernik @mattansb would you say it makes sense to have such a plot, too?

**Comment by bwiernik** [comment]
It doesn't really make sense to plot the raw residuals versus fitted values. For models that don't have equal sigma, such as weighted models or any generalized model, a raw residual versus fitted plots, can look highly degenerate just due to the varying sigma. Applied linear regression by Sanford Weisberg is a good resource on this issue. In addition, the standardized residuals have convenient values where we expect to see most residuals within plus or minus 2.

**Comment by jebyrnes** [comment]
True for glms, but, they are useful in lms - and this would give some equivalency to `plot(mod, which = 1)`

**Comment by jebyrnes** [comment]
Closing as `check_model(check = "linearity") |> plot()` gets the job done, although having it be its own function might be nice.
