### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/performance#556]
```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-cronbachs_alpha.R:14:3'): cronbachs_alpha, principal_components ──
cronbachs_alpha(pca, verbose = FALSE) (`actual`) not equal to c(PC1 = 0.1101384) (`expected`).

  `actual`: 0.09
`expected`: 0.11
── Failure ('test-cronbachs_alpha.R:15:3'): cronbachs_alpha, principal_components ──
`cronbachs_alpha(pca)` did not throw the expected warning.

[ FAIL 2 | WARN 2 | SKIP 10 | PASS 295 ]
```

**Comment by strengejacke** [comment]
These tests should all be fixed after updates were submitted to CRAN (in the order insight -> datawizard -> parameters -> performance). They all work on the dev-versions, but then I removed them from the Remotes field, because of the circular issues in the readme-check. So this should be resolved already.

**Comment by IndrajeetPatil** [comment]
Ah, okay. Good to know.

**Comment by strengejacke** [comment]
Yes, they require the latest changes in _parameters_, too.
