### ISSUE TITLE
JOSE Submission Issues

### ISSUE THREAD

**Issue by stats-tgeorge** [easystats/performance#594]
- [x] rename .bib file to paper.bib file for JOSE paper submission specifically
- [x] add specific header for **statement of need** in paper 
- [x] Re-evaluate length. 

See JOSE Submission Guidelines at [https://openjournals.readthedocs.io/en/jose/submitting.html](https://openjournals.readthedocs.io/en/jose/submitting.html)

**Comment by rempsyc** [comment]
Dear Tyler,

Thank you for these pointers! I confirm that I have renamed the .bib file and statement of need header appropriately. I have also shortened the paper. You will see that it is still longer than the average JOSE article (though still not far from some papers at JOSE). We would like to request an exception to this because we are covering guidelines and recommendations in regard to the complex question of the treatment of outliers, and shortening the paper further would not do justice to this important topic within the context of the responsible use of our package. Sincerely, the easystats team.
