### ISSUE TITLE
JOSS /J Stat Soft

### ISSUE THREAD

**Issue by strengejacke** [easystats/performance#65]
@pdwaggoner @DominiqueMakowski What do you think, is a paper about _performance_ suitable for the Journal of Statistical Software?

Here's their scope: https://www.jstatsoft.org/pages/view/mission

Maybe we can also contact the editors and ask if a paper about this package would fit into the J Stat Soft.

**Comment by pdwaggoner** [comment]
I think this is a great idea. J Stat Soft's scope suggests:

> ...dedicated to improvement of state-of-the-art in statistical computing in all areas of empirical research. Open-source code and articles are jointly reviewed and published in this journal and should be accessible to a broad community of practitioners, teachers, and researchers in the field of statistics.

Plus, the requirement is open-source, which of course everything in easystats is. 

As such, I feel like `performance` would fit well as a J Stat Soft paper. They typically require a bit more on the technical side than JOSS. So we would need to outline the paper in a way that gets into the weeds a bit more, which is actually really good because its a natural avenue to justify our coding decisions and how this is "accessible to a broad community of practitioners, teachers, and researchers in the field of statistics", per the scope of the journal. 

Just my two cents, but I would be happy to start working up an outline, and pushing forward if you both are on board. Great idea!

**Comment by strengejacke** [comment]
I would be on board! Once we know who wants to participate (currently, I see us three pkg authors as paper authors), we have to decide on "authorship rules" (who goes first/last/... etc.), and depending on that, it should be clear who contributes most to the paper.

Are there any personal preferences or jon-related necessities for anyone? For me, most preferable job would be first or last author, which would be necessary for a potential venia legendi.

**Comment by DominiqueMakowski** [comment]
Trying another journal could be great. Although I like JOSS but hey, you gotta diversify :) For the authors, that seems fair (although that makes me think that it would be cool to have this easystats preprint with all of us, but we'll see that after bayestestR). For the authors' order, I am postdoc too, so first or last would be ideal. (which makes me think that for most complicated settings with more than 3-4 people, I quite like the extensions and abuses on the authorship system, with co-firsts, co-lasts, etc. so that could be something we could consider someday (I've always wanted to see a paper with like ONLY co-first authors 😅)). For the paper itself, if we try J Stat we would have to prepare it a bit more but it's fairly doable, and we already have a robust documentation to help us out so it shouldn't be too much hassle ☺️

**Comment by strengejacke** [comment]
> so it shouldn't be too much hassle

![dont-underestimate-the-5935e7](https://user-images.githubusercontent.com/26301769/58964903-f6bb3000-87af-11e9-91ad-0ebb628d5a73.jpg)

I'd say there is quite some work, because we have to put the package into some context, both statistically and compared to other, available packages (and to elaborate on the benefits of our package).

**Comment by strengejacke** [comment]
In this sense, may I remind you of my initial statement on the JOSS submission of insight?

> Though I guess it's no big deal at least to prepare a submission to JOSS, because we have many points of the review-checklist already done, I think. We only have less content for a paper than we have for bayestestR. ;-)

And now we see what we did, quite a major revision and some effort. :-)

**Comment by DominiqueMakowski** [comment]
![image](https://user-images.githubusercontent.com/8875533/58965707-9b0a9a00-87e3-11e9-8015-30dddd7bdde6.png)

**Comment by pdwaggoner** [comment]
I agree - the three of us seems to make sense, though I’m open to whatever you guys like. I’m a faculty member, and transitioning to University of Chicago (so there will be a change in my affiliation soon). But for author order, I don’t really care about this stuff too much, so put me wherever you’d like.

**Comment by strengejacke** [comment]
co-firsts / co-lasts are also possible options for me... I somehow dislike this system where strategic thinking about a paper (author, content, which journal?) is more important than focussing on the dissemination of important and interesting research results...

**Comment by DominiqueMakowski** [comment]
> I somehow dislike this system where strategic thinking about a paper (author, content, which journal?)

Exactly, and the author's order and credit is never 100% fair (and people that do the hard work often do not get the credit they deserve but that's a whole another debate). But in this flawed context, I think pushing the envelope with co-authors makes sense as a (very) mild form of protest against an overly competitive system 😈 

And we have to admit that a paper with like 10 authors *all* co-first authors would super funny to see 😄

**Comment by pdwaggoner** [comment]
Totally agreed, that the focus (in theory) should be more on the substantive part of the work. But this is the world we live in, sadly. But even still, I try to ignore social/academic conventions as much as possible ;) So you guys determine author order, and I will go along with it.

**Comment by mattansb** [comment]
> And we have to admit that a paper with like 10 authors all co-first authors would super funny to see 😄

Can you guys have yourselves three times each as first co-authors?

**Comment by DominiqueMakowski** [comment]
Or 3 times each with each time co-first, co-second and co-last :)

**Comment by IndrajeetPatil** [comment]
Closing in favor of #221
