### ISSUE TITLE
Normality of Residuals of check_model is abnormal.

### ISSUE THREAD

**Issue by DrZhangjilin** [easystats/performance#715]
Hello, when I used `check_model` earlier to output the diagnostic results of the linear mixed effect model, the Normality of Residuals part was normal (Figure 1). But after I updated the R version and updated the package, the Normality of Residuals in the model diagnostics results of the same data and code output was abnormal (Figure 2).

However, the results of the two code runs are the same, and except for the Normality of Residuals part, the other model diagnosis parts are also completely consistent. It bothers me very much.

So my question is, what is the reason for this result? How to avoid it?

Thanks in advance and best,
Jilin Zhang

Figure 1 ![image](https://github.com/easystats/performance/assets/109844951/cd3f265e-62b3-4aba-9504-9facfccb6fdd)
Figure 2 ![image](https://github.com/easystats/performance/assets/109844951/67bef43c-d63a-4647-98fc-5758b5e936b9)

**Comment by strengejacke** [comment]
That's the detrended plot, which usually is easier to interpret since there's no angle in the reference line. Furthermore, you can see that the y-axis limits are narrower, thus the plot is "zoomed" in. You actually see the same result as before.

Two things: Install package "qqplotr" to get confidence bands. This makes it easy to judge whether the deviation is within the error bounds or not. And, try `detrend = FALSE` as argument, which should display the former normality plot.

**Comment by DrZhangjilin** [comment]
> That's the detrended plot, which usually is easier to interpret since there's no angle in the reference line. Furthermore, you can see that the y-axis limits are narrower, thus the plot is "zoomed" in. You actually see the same result as before.
> 
> Two things: Install package "qqplotr" to get confidence bands. This makes it easy to judge whether the deviation is within the error bounds or not. And, try `detrend = FALSE` as argument, which should display the former normality plot.

Thank you very much! I totally get it! Now the problem has been solved very well!
